# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: crossplane
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     namespace: crossplane
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     repoURL: https://charts.crossplane.io/stable
#     chart: crossplane
#     helm:
#       releaseName: crossplane
#   syncPolicy:
#     automated: 
#       prune: true 
#       selfHeal: true 
#       allowEmpty: false 
#     syncOptions:     
#     - CreateNamespace=true 