apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudzap
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cloudzap
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: https://github.com/jgeissler14/open-react-site
    targetRevision: HEAD
    helm:
      releaseName: cloudzap
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - CreateNamespace=true 