apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: workloads
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/argo/workloads
    repoURL: https://github.com/jgeissler14/aks_paas
    targetRevision: HEAD
    helm:
      releaseName: workloads
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - CreateNamespace=true 